name: Playwright Tests

on:
  push:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

        # TODO we need a running version of the app to run the tests against - check netlify and limit to PRs, where we get it deployed. How to check that the deployment is done?

    #   - name: Install Playwright Browsers
    #     run: npx playwright install --with-deps

    #   - name: Run Playwright tests
    #     run: npx playwright test

    #   - uses: actions/upload-artifact@v4
    #     if: ${{ !cancelled() }}
    #     with:
    #       name: playwright-report
    #       path: playwright-report/
    #       retention-days: 30
