name: Tests CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm and Node.js
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          runtime: node@26
          cache: true

      - name: Install pnpm
        run: |
          npm install --global corepack@latest
          corepack enable pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run tests
        run: |
          pnpm test

      - name: Install Playwright
        run: |
          pnpm exec playwright install

      - uses: JarvusInnovations/background-action@v2
        name: Bootstrap application
        with:
          run: |
            pnpm dev
          wait-on: |
            http://localhost:3000
            http-get://localhost:3000
          tail: true
          log-output-resume: stderr
          wait-for: 1m
          log-output: stderr,stdout
          log-output-if: true

      - name: Tests that require the resources defined above to run
        run: |
          pnpm test:e2e
